/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hasan;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hasan
 */
public class Receptionist11 extends javax.swing.JFrame {

    /**
     * Creates new form Receptionist11
     */
   // int flag1=0;
        public Receptionist11() {
        
       // Admin1 obj=new Admin1();
       // obj.aa=1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel2 = new java.awt.Panel();
        label1 = new java.awt.Label();
        jButton6 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jButton8 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        jButton10 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        jButton12 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        jButton14 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        jButton16 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        jButton18 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        jButton20 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton22 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        label2 = new java.awt.Label();
        jPanel23 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton26 = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jButton30 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 153, 153));
        panel2.setLayout(null);

        label1.setBackground(new java.awt.Color(0, 153, 153));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setName(""); // NOI18N
        label1.setText("Receptionist Area");
        panel2.add(label1);
        label1.setBounds(390, 0, 360, 90);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasan/img/exit.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel2.add(jButton6);
        jButton6.setBounds(1008, 27, 30, 30);

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasan/img/back icon.png"))); // NOI18N
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        panel2.add(jButton29);
        jButton29.setBounds(940, 30, 30, 30);

        jPanel1.add(panel2);
        panel2.setBounds(-10, 0, 1090, 90);

        jPanel2.setLayout(null);

        jPanel3.setLayout(null);
        jPanel3.add(jButton2);
        jButton2.setBounds(30, 10, 90, 110);

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText(" Appointment");
        jPanel3.add(label3);
        label3.setBounds(20, 120, 130, 40);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(160, 200, 150, 160);

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("View Appointment");
        jPanel2.add(label4);
        label4.setBounds(10, 120, 130, 40);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasan/img/clndr.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(30, 10, 90, 110);

        jPanel4.setLayout(null);

        jPanel5.setLayout(null);
        jPanel5.add(jButton7);
        jButton7.setBounds(30, 10, 90, 110);

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText(" Appointment");
        jPanel5.add(label5);
        label5.setBounds(20, 120, 130, 40);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(160, 200, 150, 160);

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setText(" Appointment");
        jPanel4.add(label6);
        label6.setBounds(20, 120, 130, 40);
        jPanel4.add(jButton8);
        jButton8.setBounds(30, 10, 90, 110);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(160, 200, 150, 160);

        jPanel6.setLayout(null);

        jPanel7.setLayout(null);
        jPanel7.add(jButton9);
        jButton9.setBounds(30, 10, 90, 110);

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setText(" Appointment");
        jPanel7.add(label7);
        label7.setBounds(20, 120, 130, 40);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(160, 200, 150, 160);

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setText(" Appointment");
        jPanel6.add(label8);
        label8.setBounds(20, 120, 130, 40);
        jPanel6.add(jButton10);
        jButton10.setBounds(30, 10, 90, 110);

        jPanel10.setLayout(null);

        jPanel11.setLayout(null);
        jPanel11.add(jButton11);
        jButton11.setBounds(30, 10, 90, 110);

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setText(" Appointment");
        jPanel11.add(label9);
        label9.setBounds(20, 120, 130, 40);

        jPanel10.add(jPanel11);
        jPanel11.setBounds(160, 200, 150, 160);

        label10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label10.setText(" Appointment");
        jPanel10.add(label10);
        label10.setBounds(20, 120, 130, 40);
        jPanel10.add(jButton12);
        jButton12.setBounds(30, 10, 90, 110);

        jPanel6.add(jPanel10);
        jPanel10.setBounds(160, 200, 150, 160);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(160, 200, 150, 160);

        jPanel12.setLayout(null);

        jPanel13.setLayout(null);
        jPanel13.add(jButton13);
        jButton13.setBounds(30, 10, 90, 110);

        label11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label11.setText(" Appointment");
        jPanel13.add(label11);
        label11.setBounds(20, 120, 130, 40);

        jPanel12.add(jPanel13);
        jPanel13.setBounds(160, 200, 150, 160);

        label12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label12.setText(" Appointment");
        jPanel12.add(label12);
        label12.setBounds(20, 120, 130, 40);
        jPanel12.add(jButton14);
        jButton14.setBounds(30, 10, 90, 110);

        jPanel14.setLayout(null);

        jPanel15.setLayout(null);
        jPanel15.add(jButton15);
        jButton15.setBounds(30, 10, 90, 110);

        label13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label13.setText(" Appointment");
        jPanel15.add(label13);
        label13.setBounds(20, 120, 130, 40);

        jPanel14.add(jPanel15);
        jPanel15.setBounds(160, 200, 150, 160);

        label14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label14.setText(" Appointment");
        jPanel14.add(label14);
        label14.setBounds(20, 120, 130, 40);
        jPanel14.add(jButton16);
        jButton16.setBounds(30, 10, 90, 110);

        jPanel12.add(jPanel14);
        jPanel14.setBounds(160, 200, 150, 160);

        jPanel16.setLayout(null);

        jPanel17.setLayout(null);
        jPanel17.add(jButton17);
        jButton17.setBounds(30, 10, 90, 110);

        label15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label15.setText(" Appointment");
        jPanel17.add(label15);
        label15.setBounds(20, 120, 130, 40);

        jPanel16.add(jPanel17);
        jPanel17.setBounds(160, 200, 150, 160);

        label16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label16.setText(" Appointment");
        jPanel16.add(label16);
        label16.setBounds(20, 120, 130, 40);
        jPanel16.add(jButton18);
        jButton18.setBounds(30, 10, 90, 110);

        jPanel18.setLayout(null);

        jPanel19.setLayout(null);
        jPanel19.add(jButton19);
        jButton19.setBounds(30, 10, 90, 110);

        label17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label17.setText(" Appointment");
        jPanel19.add(label17);
        label17.setBounds(20, 120, 130, 40);

        jPanel18.add(jPanel19);
        jPanel19.setBounds(160, 200, 150, 160);

        label18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label18.setText(" Appointment");
        jPanel18.add(label18);
        label18.setBounds(20, 120, 130, 40);
        jPanel18.add(jButton20);
        jButton20.setBounds(30, 10, 90, 110);

        jPanel16.add(jPanel18);
        jPanel18.setBounds(160, 200, 150, 160);

        jPanel12.add(jPanel16);
        jPanel16.setBounds(160, 200, 150, 160);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(160, 200, 150, 160);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(580, 370, 150, 160);

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("View Doctor");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(10, 120, 110, 34);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasan/img/doctor_assistant.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4);
        jButton4.setBounds(10, 0, 109, 107);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(590, 190, 130, 160);

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jPanel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" Patient");
        jPanel20.add(jLabel8);
        jLabel8.setBounds(10, 120, 110, 34);
        jPanel20.add(jButton21);
        jButton21.setBounds(10, 0, 109, 107);

        jPanel9.add(jPanel20);
        jPanel20.setBounds(390, 190, 130, 160);

        jPanel21.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" Patient");
        jPanel21.add(jLabel9);
        jLabel9.setBounds(10, 120, 110, 34);
        jPanel21.add(jButton22);
        jButton22.setBounds(10, 0, 109, 107);

        jPanel22.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" Patient");
        jPanel22.add(jLabel10);
        jLabel10.setBounds(10, 120, 110, 34);
        jPanel22.add(jButton23);
        jButton23.setBounds(10, 0, 109, 107);

        jPanel21.add(jPanel22);
        jPanel22.setBounds(390, 190, 130, 160);

        jPanel9.add(jPanel21);
        jPanel21.setBounds(380, 200, 130, 160);

        jButton28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasan/img/conference-call.png"))); // NOI18N
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton28);
        jButton28.setBounds(20, 10, 120, 110);

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("View Pharmacist");
        jPanel9.add(label2);
        label2.setBounds(20, 120, 118, 40);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(760, 180, 150, 170);

        jPanel23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" Patient");
        jPanel23.add(jLabel12);
        jLabel12.setBounds(10, 120, 110, 34);

        jPanel24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel24.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(" Patient");
        jPanel24.add(jLabel13);
        jLabel13.setBounds(10, 120, 110, 34);
        jPanel24.add(jButton25);
        jButton25.setBounds(10, 0, 109, 107);

        jPanel23.add(jPanel24);
        jPanel24.setBounds(390, 190, 130, 160);

        jPanel25.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel25.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" Patient");
        jPanel25.add(jLabel14);
        jLabel14.setBounds(10, 120, 110, 34);
        jPanel25.add(jButton26);
        jButton26.setBounds(10, 0, 109, 107);

        jPanel26.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel26.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" Patient");
        jPanel26.add(jLabel15);
        jLabel15.setBounds(10, 120, 110, 34);
        jPanel26.add(jButton27);
        jButton27.setBounds(10, 0, 109, 107);

        jPanel25.add(jPanel26);
        jPanel26.setBounds(390, 190, 130, 160);

        jPanel23.add(jPanel25);
        jPanel25.setBounds(380, 200, 130, 160);

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasan/img/patient11.jpg"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel23.add(jButton24);
        jButton24.setBounds(20, 0, 110, 120);

        jPanel1.add(jPanel23);
        jPanel23.setBounds(380, 200, 140, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasan/img/626640720-1024x1024.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 180, 350, 270);

        jPanel27.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel27.setLayout(null);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hasan/img/recep (2).jpg"))); // NOI18N
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel27.add(jButton30);
        jButton30.setBounds(20, 0, 109, 100);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("View  Receptionist");
        jPanel27.add(jLabel11);
        jLabel11.setBounds(0, 100, 140, 34);

        jPanel1.add(jPanel27);
        jPanel27.setBounds(760, 390, 150, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        try {
            // TODO add your handling code here:
            ViewPharmacist1Recp ob= new ViewPharmacist1Recp();
            Pharmacist ob1=new Pharmacist();
            ob1.pt=1;
            
            ob.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Receptionist11.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
       // flag1=1;
        Patient ob =new Patient();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
      Project102 ob=  new Project102();
      ob.setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            ViewDoctor ob=new ViewDoctor(); ob.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Receptionist11.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        appWork ob =new appWork();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed

        ViewRecep1Recp ob;
        try {
            ob = new ViewRecep1Recp();
            ob.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ReceptionWork.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton30ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
